// Generated by Supabase CLI — jangan diedit manual.
// Refresh dengan `supabase gen types --linked` saat schema berubah.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      categories: {
        Row: { id: string; name: string; slug: string; description: string | null; image_path: string | null; image_alt: string | null; is_visible: boolean; sort_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; name: string; slug: string; description?: string | null; image_path?: string | null; image_alt?: string | null; is_visible?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; name?: string; slug?: string; description?: string | null; image_path?: string | null; image_alt?: string | null; is_visible?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      category_spec_fields: {
        Row: { id: string; template_id: string; label: string; field_key: string; field_type: string; options: Json; unit: string | null; is_required: boolean; is_filterable: boolean; sort_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; template_id: string; label: string; field_key: string; field_type: string; options?: Json; unit?: string | null; is_required?: boolean; is_filterable?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; template_id?: string; label?: string; field_key?: string; field_type?: string; options?: Json; unit?: string | null; is_required?: boolean; is_filterable?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Relationships: [{ foreignKeyName: "category_spec_fields_template_id_fkey"; columns: ["template_id"]; referencedRelation: "category_spec_templates"; referencedColumns: ["id"] }];
      };
      category_spec_templates: {
        Row: { id: string; category_id: string; is_active: boolean; created_at: string; updated_at: string };
        Insert: { id?: string; category_id: string; is_active?: boolean; created_at?: string; updated_at?: string };
        Update: { id?: string; category_id?: string; is_active?: boolean; created_at?: string; updated_at?: string };
        Relationships: [{ foreignKeyName: "category_spec_templates_category_id_fkey"; columns: ["category_id"]; referencedRelation: "categories"; referencedColumns: ["id"] }];
      };
      landing_sections: {
        Row: { id: string; section_key: string; heading: string | null; subheading: string | null; body: string | null; config: Json; is_visible: boolean; sort_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; section_key: string; heading?: string | null; subheading?: string | null; body?: string | null; config?: Json; is_visible?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; section_key?: string; heading?: string | null; subheading?: string | null; body?: string | null; config?: Json; is_visible?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      product_documents: {
        Row: { id: string; product_id: string; label: string; file_path: string; file_size: number | null; mime_type: string | null; sort_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; product_id: string; label: string; file_path: string; file_size?: number | null; mime_type?: string | null; sort_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; product_id?: string; label?: string; file_path?: string; file_size?: number | null; mime_type?: string | null; sort_order?: number; created_at?: string; updated_at?: string };
        Relationships: [{ foreignKeyName: "product_documents_product_id_fkey"; columns: ["product_id"]; referencedRelation: "products"; referencedColumns: ["id"] }];
      };
      product_spec_values: {
        Row: { id: string; product_id: string; field_id: string; value_text: string | null; value_number: number | null; value_boolean: boolean | null; value_select: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; product_id: string; field_id: string; value_text?: string | null; value_number?: number | null; value_boolean?: boolean | null; value_select?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; product_id?: string; field_id?: string; value_text?: string | null; value_number?: number | null; value_boolean?: boolean | null; value_select?: string | null; created_at?: string; updated_at?: string };
        Relationships: [{ foreignKeyName: "product_spec_values_field_id_fkey"; columns: ["field_id"]; referencedRelation: "category_spec_fields"; referencedColumns: ["id"] }];
      };
      products: {
        Row: { id: string; category_id: string; name: string; slug: string; summary: string | null; description: string | null; main_image_path: string | null; main_image_alt: string | null; gallery: Json; tags: string[]; is_visible: boolean; sort_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; category_id: string; name: string; slug: string; summary?: string | null; description?: string | null; main_image_path?: string | null; main_image_alt?: string | null; gallery?: Json; tags?: string[]; is_visible?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; category_id?: string; name?: string; slug?: string; summary?: string | null; description?: string | null; main_image_path?: string | null; main_image_alt?: string | null; gallery?: Json; tags?: string[]; is_visible?: boolean; sort_order?: number; created_at?: string; updated_at?: string };
        Relationships: [{ foreignKeyName: "products_category_id_fkey"; columns: ["category_id"]; referencedRelation: "categories"; referencedColumns: ["id"] }];
      };
      profiles: {
        Row: { id: string; email: string; full_name: string | null; is_admin: boolean; created_at: string; updated_at: string };
        Insert: { id: string; email: string; full_name?: string | null; is_admin?: boolean; created_at?: string; updated_at?: string };
        Update: { id?: string; email?: string; full_name?: string | null; is_admin?: boolean; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      site_settings: {
        Row: { id: number; brand_name: string; brand_tagline: string | null; contact_email: string | null; contact_phone: string | null; contact_address: string | null; seo_title: string | null; seo_description: string | null; whatsapp_number: string | null; whatsapp_template: string; updated_at: string };
        Insert: { id?: number; brand_name?: string; brand_tagline?: string | null; contact_email?: string | null; contact_phone?: string | null; contact_address?: string | null; seo_title?: string | null; seo_description?: string | null; whatsapp_number?: string | null; whatsapp_template?: string; updated_at?: string };
        Update: { id?: number; brand_name?: string; brand_tagline?: string | null; contact_email?: string | null; contact_phone?: string | null; contact_address?: string | null; seo_title?: string | null; seo_description?: string | null; whatsapp_number?: string | null; whatsapp_template?: string; updated_at?: string };
        Relationships: [];
      };
    };
    Functions: {
      has_no_admin: { Args: never; Returns: boolean };
      is_admin: { Args: never; Returns: boolean };
    };
  };
};
